### PR TITLE
Added oci example add the provisioner parameter in docs

### PR DESCRIPTION
**Pull request by 7h3-3mp7y-m4n**
### Added **oci** example add the provisioner parameter in docs
Provide information on the motivation for why you have made this change.

## What does this change do?
Added the missing documentation.
Provide a description of what this pull request does.

## What is your testing strategy?

Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.
I read the Readme.md to check it locally 
here are my changes 
for `score-k8s`
Screenshot 2024-10-20 at 3 16 39 AM

for `score-compose`
Screenshot 2024-10-20 at 3 19 22 AM
 
## Is this related to any issues?
**YES**
If this pull request is related to any other pull request or issue, or resolves any issues - then link all related pull requests and issues here.
[Issue](https://github.com/score-spec/score-compose/issues/178)
## Have you read the [Contributing Guidelines](CONTRIBUTING.md)?

- [x] I have read the [Contributing Guidelines](CONTRIBUTING.md)

### CODE REVIEW

**Review by mathieu-benoit — COMMENTED** [review]
What about having the same formatting/output than the actual `--help` command with the bullets points you did?
image

**Comment by 7h3-3mp7y-m4n** [comment]
> What about having the same formatting/output than the actual `--help` command with the bullets points you did? image

Yes, We can do that :)

**Comment by mathieu-benoit** [comment]
Bumping this one since we now have this new `score-go` release https://github.com/score-spec/score-go/releases/tag/v1.8.4 integrated in both `score-compose` and `score-k8s`. Thanks in advance!

**Comment by 7h3-3mp7y-m4n** [comment]
Okay, let me beautify it a little like bullet points?

**Comment by 7h3-3mp7y-m4n** [comment]
Screenshot 2024-11-03 at 9 13 53 PM

**Comment by mathieu-benoit** [comment]
Associated releases https://github.com/score-spec/score-k8s/releases/tag/0.1.15 and https://github.com/score-spec/score-compose/releases/tag/0.20.0 are out, merging, thanks!

**Review by mathieu-benoit — APPROVED** [review]
LGTM

**Pull request merged**
