### PR TITLE
#51 Added docs for completion command in score-k8s

### PR DESCRIPTION
**Pull request by Somsubhra**
## What is the motivation?

Added documentation for the completion command added to score-k8s to generate shell completions as a part of PR https://github.com/score-spec/score-k8s/pull/60 Issue https://github.com/score-spec/score-k8s/issues/51

## What does this change do?

Add documentation for the completion command added to score-k8s

## Is this related to any issues?

https://github.com/score-spec/score-k8s/issues/51

## Have you read the [Contributing Guidelines](CONTRIBUTING.md)?

- [x] I have read the [Contributing Guidelines](CONTRIBUTING.md)

### CODE REVIEW

**Comment by mathieu-benoit** [comment]
Hi @Somsubhra, thanks for adding this, I'll review soon this other PR https://github.com/score-spec/score-k8s/issues/51 as it's a dependencies on this one (and a release associated to this too).

In the meantime, we just merged this in `main` https://github.com/score-spec/docs/pull/123, could you please update your branch accordingly and also add this new command on this new page https://docs.score.dev/docs/score-implementation/score-k8s/cli/? Thanks!

**Comment by Somsubhra** [comment]
@mathieu-benoit - updated the documentation on the new page. Thanks!

**Comment by mathieu-benoit** [comment]
Waiting for https://github.com/score-spec/score-k8s/pull/60 to be completed, merged and released in order to proceed here.

**Comment by mathieu-benoit** [comment]
New version of `score-k8s` including this feature now released: https://github.com/score-spec/score-k8s/releases/tag/0.1.14, let's merge this one now.

**Review by mathieu-benoit — APPROVED** [review]
LGTM

**Pull request merged**
